pages:
    image: nixos/nix
    script:
        - nix-env -iA nixos.cachix
        - cachix use miso-haskell
        - nix-shell --run "cabal --http-transport=plain-http build"
        - cp `find dist-newstyle -name all.js` public/
    artifacts:
        paths:
            - public
    only:
        - master

