pages:
    image: juliendehos/miso-invaders
    script:
        - nix-build
        - cp result/bin/miso-invaders.jsexe/* public/
    artifacts:
        paths:
            - public
    only:
        - master

