pages:
    image: juliendehos/cicd:miso-invaders
    script:
        - nix-shell --run "cabal --http-transport=plain-http build"
        - cp dist/build/miso-invaders/miso-invaders.jsexe/all.js public/
    artifacts:
        paths:
            - public
    only:
        - master

